name: Build Micro for Windows ARM32

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build for Windows ARM32
      run: |
        cd cmd/micro
        GOOS=windows GOARCH=arm CGO_ENABLED=0 go build -ldflags="-s -w -X 'main.Version=2.0.14' -X 'main.CommitHash=${{ github.sha }}' -X 'main.CompileDate=${{ github.event.head_commit.timestamp }}'" -o micro.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: micro-arm32
        path: cmd/micro/micro.exe
